MikeRogers0/MikeRogersIO

.rubocop.yml
.travis.yml
Gemfile
Gemfile.lock
README.md
package.json
spec/features/valid_html_spec.rb
spec/features/visting_pages_spec.rb
spec/spec_helper.rb

This is a quick Rspec test to check pages can load correctly. Initially I wanted it to check pages were valid, but it turned into a big PITA.

Adding CI to confirm build works

---

config.rb
netlify.toml

Setup my defaults via the TOML instead of the web interface.

Configuring Netfily processing via toml

---

source/layouts/post.erb
source/stylesheets/_codefund.scss
source/stylesheets/site.css.scss.erb

I want to see if I can make any extra cash from my blog posts - Experimenting with options.

Adding CodeFund HTML snippet

---

source/blog/2020-06-26-heys-gemfile.html.md
source/blog/2020-06-28-reviewing-the-hey-gemfile.html.md

I wanted to write some notes on the HEY gemfile.

Reviewing HEY's gemfile

---

docker-compose.yml

My local docker was kind of slow, so I made some tweaks to fix that :D

Speeding up startup times by caching node_modules

---

source/layouts/layout.erb
source/layouts/post.erb

I'm trying to earn a bit of extra cash from my blog, so experimenting with Amazon ads.

Throwing up an Amazon Advert to help earn some cash

---

src/_components/footer.liquid

Making footer look decent on mobile

---

docker-compose.yml
frontend/styles/tailwindcss/components/article.css
frontend/styles/tailwindcss/custom_base.css
package.json
src/_layouts/default.html
src/_posts/2019-03-03-ruby-iso-date-formats.md
tailwind.config.js
webpack.config.js
yarn.lock

Improving the accessibility a touch to make life better for everyone :D

Tweaking Typography & screen reader skip content link

---

netlify.toml

Netlify has plugins :O So experimenting with the sitemap submission one.

Auto submitting sitemap on build

---

.github/workflows/build-data.yml
Gemfile
Gemfile.lock
Rakefile
lib/source.rb
lib/source/base.rb
lib/source/github_pull_requests.rb
src/_components/index/posts.liquid
src/_components/index/pull_requests.liquid
src/_components/posts/_post.liquid
src/_components/pull_requests/_pull_request.liquid
src/_data/distinct_github_pull_requests.yml
src/_data/github_pull_requests.yml
src/index.html

I wanted a way to show what I've been working on with zero effort to update my site.
This pull in PRs once a week to display on the homepage.

Pulling latest merged PRs from GitHub

---

.github/FUNDING.yml
src/_layouts/post.html

GitHub sponsors is kind of a circle jerk, so switching it out with one off payments.

Ditch GitHub sponsors

---

src/_posts/2020-07-28-active-record-connection-timeout-exceptions.md

A quick write up on how I fixed some timeout issue on Heroku.

Fixing ActiveRecord::ConnectionTimeoutError exceptions post

---

netlify.toml
plugins/purgecss_builder.rb
tailwind.config.js

It sometimes missed markdown aspects, so making sure it keeps them :D

Running PurgeCSS Post build

---

src/_posts/2020-08-17-ruby-using-the-double-splat-with-keyword-arguments.md

I used the double splat recently & it was mentioned in a meetup, so I thought it would be neat to make a note of how it works.

Post: How to use double splat

---

.github/workflows/spellcheck.yml

I setup Typo CI as an action, so giving that a whirl!

Adding TypoCI/spellcheck-action

---

src/_components/books/_book.liquid
src/_components/footer.liquid
src/_data/books.yml
src/books-ive-read.html
src/books.html

I want to make a little Amazon Affiliate money, I think adding links to books I've read is acceptable :)

Adding Books I've read page

---

src/_posts/2020-11-11-how-to-be-serverless-on-heroku.md

I moved some jobs off to One-off dynos on Heroku & it saved me a bunch of Money. Woop.

Post: How To Be Serverless on Heroku

---

src/_posts/2020-12-12-offline-rails.md
src/_posts/2020-12-14-how-to-make-rails-work-offline-via-service-workers.md

I put together my notes on PWAs & it became a blog post.

Adding post on Offline Rails

---

src/_posts/2015-01-10-how-to-build-a-contact-form-in-ruby-on-rails.md
src/_posts/2015-01-14-displaying-twitter-feed-rails-4.md

I had a start of the year tidy up & moved my demo repos into https://github.com/mikerogers0-youtube - It means I can make lots of demo repos without worrying about distracting my current setup.

Moving my YouTube repos over to their own account

---

.github/workflows/build-data.yml

I don't need to manually manage that bundle cache anymore - HUZZAH!

Using ruby/setup-ruby built in ruby cache

---

netlify.toml

The browser spec changed & now I have to update the CSP again. I might remove it, but for now I'm just going to experiment with options

Simplifying Content-Security-Policy

---

.github/workflows/build-data.yml
bin/netlify.sh
bridgetown.config.yml
netlify.toml
package.json
plugins/purgecss_builder.rb
plugins/social_image_builder.rb
postcss.config.js
purgecss.config.js
sync.js
webpack.config.js
yarn.lock

This should speed up the build time massively

Using Bridgetown::Cache to cache pngs between builds

---

netlify.toml

https://andycroll.com/ruby/opt-out-of-google-floc-tracking-on-netlify
Seriously, google can get fucked for requiring us to opt-out.

Opt'ing out of Google’s FLoC User Tracking

---

Gemfile.lock
frontend/styles/components/article.css
frontend/styles/components/footer.css
plugins/filters/youtube.rb
src/_layouts/video.html

This cuts down the content from YouTube when I render it out on this site. It does kind of suck, but I think ti's nicer then nothing :)

Using a custom filter to change the content if YouTube Description

---

.github/workflows/build-data.yml
Gemfile.lock

I had it configured to only run on Macos somehow - I need to lookout to not do that again.

bug: Fixing data update being unable to run

---

.github/workflows/build-data.yml
lib/video.rb

I noticed when I ran the pull data task it didn't add new videos, so fixing that.

fix: Add new videos when running automated scripts
